projects:
  NameThatCatApi:
    schemaPath: src/graphql/schema.json
    includes:
      - graphql/queries
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: angular
        generatedFileName: src/app/API.service.ts
        docsFilePath: graphql
