version: 0.2

phases:
  install:
    commands:
      - npm ci
      - npm install -g @angular/cli

  build:
    commands:
      - echo Building project...
      - ng build --prod
  post_build:
    commands:
      - echo Build completed!

artifacts:
  files:
    - dist/**/*