version: 0.2

phases:
  install:
    commands:
      - npm install -g @angular/cli

  build:
    commands:
      - echo Testing project...
      - npm test

  post_build:
    commands:
      - echo Unit testing completed!
