version: 0.2

phases:
  install:
    commands:
      - npm ci
      - npm install -g @angular/cli

  pre_build:
    on-failure: ABORT
    commands:
      - echo Linting Project...
      - ng lint
      - echo Testing projest...
      -npm test

  build:
    commands:
      - echo Building project...
      - ng build --prod

  post_build:
    commands:
      - echo Build completed!

artifacts:
  files:
    - dist/**/*