version: 0.2
env:
  variables:
    BUILD_ENV: prod

phases:
  install:
    commands:
      - npm install -g @angular/cli
  build:
    commands:
      - echo Building project...
      - npm run build --${BUILD_ENV}
  post_build:
    commands:
      - echo Build completed!

artifacts:
  files:
    - dist/**/*